query BRAND(
  $slug: String!
  $products_per_page: Int = 10
  $product_page: Int = 1
) {
  brand(slug: $slug) {
    id
    title
    slug
    products(per_page: $products_per_page, page: $product_page) {
      nodes {
        id
        slug
        title
        price
        date
        excerpt
        description
        images {
          id
          actual
          medium
          thumb
          large
        }
        gender
        brands {
          id
          title
          slug
        }
      }
      meta {
        count
        lastPage
        currentPage
        total
      }
    }
  }
}
