query PRODUCT($slug: String!) {
  product(slug: $slug) {
    id
    title
    description
    sku
    gender
    date
    images {
      id
      actual
      thumb
      medium
      large
    }
    groups {
      id
      title
      slug
    }
    brands {
      id
      title
      slug
    }
  }
}
